[profile.default]
fs_permissions = [{access = "read", path = "./out"}]
libs = ["lib", "./node_modules"]
out = "out"
src = "src"

[profile.fork]
libraries = [
  "./node_modules/poseidon-solidity/PoseidonT3.sol:PoseidonT3:0x3333333C0A88F9BE4fd23ed0536F9B6c427e3B93",
]
